DESCRIBE COUNTRIES;
`
SELECT EMPLOYEE_ID||', '||FIRST_NAME||', '||LAST_NAME||', '||EMAIL||', '||PHONE_NUMBER||', '||HIRE_DATE||', '||JOB_ID||', '||SALARY||', '||COMMISSION_PCT||', '||MANAGER_ID||', '||DEPARTMENT_ID "NUME COLOANA" FROM EMPLOYEES;

SELECT DISTINCT department_id FROM employees;

SELECT EMPLOYEE_ID, FIRST_NAME  FROM EMPLOYEES WHERE DEPARTMENT_ID=80 OR DEPARTMENT_ID=40; 

SELECT EMPLOYEE_ID, SALARY  FROM EMPLOYEES WHERE SALARY > 5000 AND (DEPARTMENT_ID=30 OR DEPARTMENT_ID=50); 


SELECT EMPLOYEE_ID, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID NOT IN (10,30,50,70,90);

SELECT EMPLOYEE_ID, SALARY  FROM EMPLOYEES WHERE SALARY>=7000 AND SALARY<=10000;

SELECT EMPLOYEE_ID, SALARY  FROM EMPLOYEES WHERE  SALARY BETWEEN 7000 AND 10000;

SELECT FIRST_NAME, JOB_ID,HIRE_DATE  FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '20-FEB-1987' AND '1-MAY-1989' ORDER BY HIRE_DATE;

DESCRIBE DUAL;

SELECT 2+2 FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT TO_CHAR (SYSDATE,'DD/MM/YYYY HH24:MI:SS') FROM DUAL;

SELECT EMPLOYEE_ID, FIRST_NAME FROM employees WHERE FIRST_NAME LIKE ('%l%l%');

SELECT EMPLOYEE_ID, FIRST_NAME FROM employees WHERE LOWER (FIRST_NAME) LIKE ('%l%l%');

SELECT EMPLOYEE_ID, SALARY FROM EMPLOYEES WHERE SALARY LIKE ('__5%');

select last_name, job_id FROM employees WHERE manager_id IS NULL;

SELECT FIRST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL ORDER BY SALARY DESC, COMMISSION_PCT DESC;

SELECT FIRST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES ORDER BY SALARY DESC, COMMISSION_PCT DESC;

SELECT FIRST_NAME, JOB_ID, SALARY FROM EMPLOYEES WHERE (LOWER(JOB_ID) LIKE ('%clerk%') OR LOWER(JOB_ID) LIKE ('%rep%')) AND SALARY NOT IN (1000,2000,3000); 

SELECT FIRST_NAME, SALARY, COMMISSION_PCT  FROM EMPLOYEES WHERE SALARY> 5*SALARY*NVL(COMMISSION_PCT,0);

SELECT FIRST_NAME, SALARY, COMMISSION_PCT  FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL;

